### ISSUE TITLE
[기능 추가] double down 기능 구현

### ISSUE THREAD

**Issue by 95hongju** [ParkJongSang/CNU22_SpringBlackJack#13]
처음 두 장의 카드를 받은 후, 3번째 카드 한 장만 더 받더라도, 딜러를 이길 수 있다고 생각 될 경우, (4번째 카드는 받을 수 없음.) 더블다운(double down) 할 수 있습니다. 즉, 배팅 금액을 두 배로 하고, 오직 한 장의 카드만을 더 받습니다.

**Comment by 95hongju** [comment]
처음 두 장의 카드를 받은 후, 3번째 카드 한 장만 더 받더라도, 딜러를 이길 수 있다고 생각 될 경우, (4번째 카드는 받을 수 없음.) 더블다운(double down) 할 수 있습니다. 즉, 배팅 금액을 두 배로 하고, 오직 한 장의 카드만을 더 받습니다.

**Comment by c201200740** [comment]
1. 오로지 자신의 패에 2장을 보유하고 있는 상태에서만 더블다운 신청가능합니다.
(현재 히트 후 더블다운이 가능하게 되어 있음)
2. 더블다운 신청 후, 딜러에게 졌을 때 배팅금액의 2배를 잃어야 합니다.
(현재 배팅금액의 3배를 잃고 있음)
아직 위의 2가지 조건이 충족되지 않았습니다. 따라서 다시 오픈합니다.
